spring.application.name=EmployeeManagementSystem

logging.level.org.springframework.security=DEBUG

#Data source

spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt-secret=thisIsJwtKeyToGenerateTheTokenThisShouldBeMoreThen32Characters
app.jwt-expiry=3600000

